### ISSUE TITLE
rans64.h:44:35: error: __int128 is not supported on this target

### ISSUE THREAD

**Issue by swaiwi** [rygorous/ryg_rans#8]
I want to use rans64.h in arm android device, but got error like this:
rans64.h:44:35: error: __int128 is not supported on this target.
how can I fix the bug?

**Comment by rygorous** [comment]
This repository is intended as a precise description of the algorithm, _not_ library code that should ever be used in any application. (It's got no proper bounds checking! You can't ship this in anything!) As for the version using 64-bit renormalization, yes, that needs a compiler with support for 128-bit integers. If you don't have such a compiler, you can't use rans64. You can use the other variants (but still not the ryg_rans code).

**Comment by tansy** [comment]
> how can I fix the bug?

You can get newer compiler.
__int128 is supported on 64-bit (x86_64) for long time. It's not supported in 32-bit systems at all.
Don't know about arm but as __int128_t is emulated by using pairs of int64_t in the same way as 64bit integers are emulated with 32bit ones on 32bit compiles, 64-bit arm should have it. 32-bit Won't. Rans64 on 32-bits is really slow (3-4 times encoding and ~15%-20% decoding). It makes no sens to use it in 32-bit architecture.
